### ISSUE TITLE
Register page missing fields and style

### ISSUE THREAD

**Issue by sorinburghiu2323** [sorinburghiu2323/4ums#46]
## Description
The register page currently displays things that shouldn't be on it as well as it's missing fields that should be part of the registration process.

## TODO
- [x] Remove navbar from register page.
[Cancelled] Add optional field `bio` and connect that to the API field `description`.
- [x] Add checkbox for applying for a lecturer account and use the adequate API field for it.
- [x] Include a pop up/another page for the terms and conditions (can be found in the shared drive).

**Comment by hiba-aldalaty** [comment]
I don't know if having a bio in the registration page makes sense, it usually is something you add when you have an account

**Comment by sorinburghiu2323** [comment]
> I don't know if having a bio in the registration page makes sense, it usually is something you add when you have an account

I see. I think a description box would also take too much space from the register which is bad for design.
