### ISSUE TITLE
Posts should show the number of comments

### ISSUE THREAD

**Issue by sorinburghiu2323** [sorinburghiu2323/4ums#66]
## Description
Currently posts do not display the number of comments. This is already implemented on the api, it just needs to be displayed in the frontend.

# TODO
- [x] Display number of posts before clicking on a post to expand it (next to the likes perhaps with some icon)
- [x] If the post has no comments yet, do not display it.
- [x] Display the number of posts on an expanded post too.
